#!/bin/bash

source $CLUSTER_UTIL_ROOT/share/cluster-lib.sh

# this part does the checking of the command line arguments

while getopts "ha:u:" option; do

    case $option in
        h)
            # -h: displays help message
            echo "Usage: cluster-userattr [-a <attribute>] [-u <userid>]"
            exit 0
            ;;
        a)
            ATTR=$OPTARG
            ;;
        u)
            USERID=$OPTARG
            ;;
        \?)
            # invalid options
            echo "Invalid option -${option}" >&2
            ;;
    esac
done

shift $(($OPTIND - 1))

if [ -z $USERID ]; then
    USERID=$USER
fi

# composing common name for binding user for this search
bind_user="CN=ldapbind,OU=Functional Users and Groups,OU=dccn,DC=dccn,DC=nl"
uinfo=$( getent passwd | grep ${USER} )

if [ $? -eq 0 ]; then
    uname=$( echo ${uinfo} | awk -F ':' '{print $5}' )
    gname=$( echo ${uinfo} | awk -F ':' '{print $6}' | awk -F '/' '{print $(NF-1)}' )
    bind_user="CN=${uname},OU=${gname},OU=dccn,DC=dccn,DC=nl"
fi

echo "searching by user: ${bind_user} for user ${USERID}"
ldapsearch -LLL -h dccn-w001.dccn.nl -D "${bind_user}" -W -b 'OU=dccn,DC=dccn,DC=nl' "(&(sAMAccountName=${USERID}))" ${ATTR}