#!/bin/env tclsh
setenv MNI_DIR $env(FREESURFER_HOME)/mni
setenv MNI_PERL5LIB $env(FREESURFER_HOME)/mni/lib/perl5/5.8.5
setenv FS_OVERRIDE 0
setenv FSF_OUTPUT_FORMAT nii.gz
setenv OS Linux
setenv FMRI_ANALYSIS_DIR $env(FREESURFER_HOME)/fsfast
setenv PERL5LIB $env(FREESURFER_HOME)/mni/lib/perl5/5.8.5
prepend-path PATH $env(FREESURFER_HOME)/mni/bin
prepend-path PATH $env(FREESURFER_HOME)/tktools
prepend-path PATH $env(FREESURFER_HOME)/fsfast/bin
prepend-path PATH $env(FREESURFER_HOME)/bin
setenv FIX_VERTEX_AREA {};
setenv SUBJECTS_DIR $env(FREESURFER_HOME)/subjects
setenv MINC_LIB_DIR $env(FREESURFER_HOME)/mni/lib
setenv MNI_DATAPATH $env(FREESURFER_HOME)/mni/data
setenv MINC_BIN_DIR $env(FREESURFER_HOME)/mni/bin
setenv FSFAST_HOME $env(FREESURFER_HOME)/fsfast
setenv FUNCTIONALS_DIR $env(FREESURFER_HOME)/sessions
setenv LOCAL_DIR $env(FREESURFER_HOME)/local
