.\" Process this file with
.\" groff -man -Tascii vncinfo.1
.\"
.TH MARTINI 1 "29 october 2010" dccn "Mentat Cluster Utilities"
.SH NAME
martini \- suggests a host to login to
.SH SYNOPSIS
.B martini
.SH DESCRIPTION
Martini searches for the best cluster node to login to, based on current memory usage.
.SH AUTHOR
Stephen Whitmarsh <stephen.whitmarsh@donders.ru.nl>
.SH "SEE ALSO"
.BR cluster-memfree (1)
