.TH VNCMANAGER 1 "20 june 2006" dccn "Mentat Cluster Utilities"
.SH NAME
vncmanager \- start, stop, list and configure vncservers
.SH SYNOPSIS
.B vncinfo 
.SH DESCRIPTION
Vncmanger is an interactive shell script that helps you starting, stopping,
listing and configuring vnc server sessions.
.SH FILES
.I /opt/cluster/machines
.RS
Containes the list of machines that are searched for running vncservers.
.SH AUTHOR
Bram Daams <bram.daams@donders.ru.nl>
.SH "SEE ALSO"
.BR vncinfo (1)
.BR vncserver (1)
.BR cluster-vncserver (1)
